### ISSUE TITLE
Empty field to delete it?

### ISSUE THREAD

**Issue by Hexaae** [RafaelDeJongh/WooCommerce-Barcode#1]
Would be handy to delete the Barcode entering a null string and saving product....

**Comment by RafaelDeJongh** [comment]
> Would be handy to delete the Barcode entering a null string and saving product....

With not only WordPress but also WooCommerce and the POS plugin have been updated since the creation and public release of this plugin, I wouldn't actually even recommend using it if it still somewhat works. 

Feel free to make a fork or submit one that can be updated as the owner where I made this plugin for changed POS systems after a year and thuss further development of this plugin development was completely stopped and as I also do not recommend this POS for any actual business with more than 5 people in the store I therefor also don't see really no need to continue any development of it. 

You are free however to do with it as you see fit in accordance with the WordPress GPL license.
